# Generated by Django 5.2.7 on 2025-12-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='destacado',
        ),
        migrations.AddField(
            model_name='tour',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
