# Generated by Django 5.2.7 on 2026-01-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
