# Generated by Django 5.2.7 on 2025-12-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0002_remove_tour_destacado_tour_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
