# Generated by Django 5.2.7 on 2025-12-29 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0003_tour_destacado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='personas',
            field=models.PositiveIntegerField(),
        ),
    ]
