# Generated by Django 5.2.7 on 2025-12-29 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0004_remove_reserva_fecha_reserva_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitioturistico',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitioturistico',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitioturistico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='sitios/'),
        ),
        migrations.AddField(
            model_name='sitioturistico',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
